### ISSUE TITLE
How did you fix the issue regarding creating a user in a anonymous state?

### ISSUE THREAD

**Issue by WeTurkstra** [starckio/Userskit#1]
I just checked this repo because i need a way to create a user while not logged in. 
But kirby3 is not letting me create a user when iam anonymous.

It looks like your repo is also not allowing  me to register. 

could you please provide some info on this subject. 
Thanks!

**Comment by starckio** [comment]
Ok, I did not rename the account creation controllers.
I just updated the repo.
Download and tell me if it works on your side.

**Comment by WeTurkstra** [comment]
Hey man! Thanks for the reply. I have to tell you that i used your fix in my own code. And the impersonte function was the thing i was looking for. 

Kirby is a great cms with hidden features :D
